# Generated by Django 4.2.2 on 2023-06-30 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cats',
            old_name='name',
            new_name='nombre',
        ),
    ]
