# Generated by Django 4.2.2 on 2023-08-18 15:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarterApp', '0003_birds_dogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cat_images/'),
        ),
        migrations.AddField(
            model_name='cats',
            name='texto_formateado',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
