# Generated by Django 4.2.2 on 2023-08-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarterApp', '0004_cats_imagen_cats_texto_formateado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cats',
            name='imagen',
        ),
    ]
