# Generated by Django 4.2.2 on 2023-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarterApp', '0005_remove_cats_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cat_images'),
        ),
    ]
